#!/bin/sh

# This script is executed AFTER the Debian package is INSTALLED
# For information about this file, see http://www.debian.org/doc/manuals/debian-faq/ch-pkg_basics.en.html#s-maintscripts.

mv "/var/jb/Library/Frameworks/RevealServer.framework/RevealServer" "/var/jb/Library/MobileSubstrate/DynamicLibraries/RevealServer"
ln -fs "/var/jb/Library/MobileSubstrate/DynamicLibraries/RevealServer" "/var/jb/Library/Frameworks/RevealServer.framework/RevealServer"
